### ISSUE TITLE
indy-pool 설치 및 구성 

### ISSUE THREAD

**Issue by anstnsp** [anstnsp/Hyperledger-indy-practice#12]
# Indy-node 설치 및 구성 

## 1.소개
로컬에서 docker를 이용해 indy-pool를 설치 및 구성하는 방법을 설명합니다. 

또한 이 글은 아래 링크들을 참고 했습니다.
[Installation and configuration of Indy-Node](https://github.com/hyperledger/indy-node/blob/master/docs/source/installation-and-configuration.md#installation-and-configuration-of-indy-node)
[Setting up a New Network](https://github.com/hyperledger/indy-node/blob/master/docs/source/NewNetwork/NewNetwork.md#ii-assign-network-trustees)
[Indy File Folders Structure Guideline](https://github.com/hyperledger/indy-node/blob/stable/docs/source/indy-file-structure-guideline.md)
[Create a Network and Start Nodes](https://hyperledger-indy.readthedocs.io/projects/node/en/latest/start-nodes.html)
[Hands on Walkthrough](https://github.com/hyperledger/indy-node/blob/master/sample/Network/README.md)
[VON Network](https://github.com/bcgov/von-network)

## 2.Indy-File Folder 구조 
`/etc/indy` : 
   - Indy-config files
	   - indy.env : Node이름, Node IP, Node Port , Client IP 등...
	   - indy_config.py : Network이름, 각종디렉토리 경로 
   - other config files (such as service config)
		-	 기타구성 파일

`/var/lib/indy` : 
-   ledger (transaction log, states)
-   Genesis transaction files
-   Node keys (transport and BLS)

`var/lib/backup` : 
- backup 파일들 

`var/lib/plugins` :
- plugin 들 
 	
 	 
 `/var/log/indy` :
-  indy 로그파일들  

### 3-1.Dockerfile 만들기 & 이미지 빌드 
`indy-node`를 ubuntu에 설치하는 방법은 아래와 같습니다. 
([여기](https://hyperledger-indy.readthedocs.io/projects/node/en/latest/start-nodes.html)에서 `Install Indy Node`참고)

```shell
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CE7709D068DB5E88
sudo bash -c 'echo "deb https://repo.sovrin.org/deb xenial stable" >> /etc/apt/sources.list'
sudo apt-get update
sudo apt-get install indy-node
```

위를 바탕으로 Dockerfile`(indy-node.docekrfile)`을 만듭니다.  
현재`stable` 인 `indy-node`는 버전 1.12.4 입니다. 

아래 Dockerfile 예제에서 EXPOSE는 테스트를 위한 임의의 포트개방입니다.
```shell
FROM  ubuntu:16.04

RUN  apt-get  update  -y  &&  apt-get  install  -y  \
git  \
apt-transport-https  \
ca-certificates  \
pwgen

RUN  apt-key  adv  --keyserver  keyserver.ubuntu.com  --recv-keys  CE7709D068DB5E88
RUN  bash  -c  'echo  "deb  https://repo.sovrin.org/deb  xenial  stable"  >>  /etc/apt/sources.list'
RUN  apt-get  update
RUN  apt-get  install  -y  indy-node

USER  indy
WORKDIR  /home/indy

EXPOSE  9701  9702  9703  9704  9705  9706  9707  9708
```

**도커 이미지 빌드** 
방금만든 Dockerfile이 있는 곳에가서 아래 명령 실행.
```
docker build -t indy-node2:1.0 -f indy-node.dockerfile .
```
### 3-2.Seed 생성 

호스트머신(노트북)에서 `pwgen` 을 통해 각각의 seed를 생성.[(참고)](https://github.com/hyperledger/indy-node/blob/master/docs/source/installation-and-configuration.md#generate-a-seed)
> Seed를 아는 사람은 자신의 지갑에 똑같은 DID, Verkey를 다시 생성하여 원장을 관리하는 데 사용할 수 있기 때문에 꼭 주의해서 보관해야 합니다.
> 즉, Seed를 아는것은 DID, Verkey를 알고 있는 것 입니다.

**3-2-1. pwgen 설치**
```
brew install pwgen 
```

**3-2-2. 아래와 같은 스크립트로 각각의 Seed 생성** 
> Validator Node의 Seed는 노드초기화(init_indy_node)시 만들어 지기 때문에 아래처럼 Seed를 먼저 생성해도 되고 또는 초기화를 통해 나온 시드를 저장해서 사용하거나 둘중 하나 택일. 
```shell
function  genSeed() {
	echo  $(pwgen -s 32 -1)
}

#Trustee 시드생성 
if [ "${role}" == "trustees" ]; then
	for  ((var=1 ; var <=  $TRUSTEE_CNT ; var++));
	do
		echo  $(genSeed) > scripts/seeds/${role}/${role}-seed$var
	done
fi

#Steward 시드생성
if [ "${role}" == "stewards" ]; then
	for  ((var=1 ; var <=  $NODE_CNT ; var++));
	do
		echo  $(genSeed) > scripts/seeds/${role}/${role}-seed$var
	done
fi

#Validator Node 시드생성
if [ "${role}" == "nodes" ]; then
	for  ((var=1 ; var <=  $NODE_CNT ; var++));
	do
		echo  $(genSeed) > scripts/seeds/${role}/${role}-seed$var
	done

fi
```

**3-2-2. Indy-Pool 구성을 Node 및 재료 준비** 

 - Node 초기화를 위한 docker-compose 파일 및 쉘파일 준비

```yml
version: '3'
services:

  node1:
    container_name: node1 
    image: indy-node2:1.0
    command: 'bash -c ''./home/indy/scripts/init_node.sh 1 test-network && sleep 9999'''
    # command: 'bash -c ''sleep 9999'''
    networks:
      - anstnsp
    ports:
      - 9701:9701
      - 9702:9702
    environment:
      - NODE_SEED=/home/indy/scripts/seeds/nodes/nodes1-seed
    volumes:
      - node1-data:/var/lib/indy
      - ./scripts:/home/indy/scripts:ro
      
  node2:
    container_name: node2
    image: indy-node2:1.0
    command: 'bash -c ''./home/indy/scripts/init_node.sh 2 test-network'''
    networks:
      - anstnsp
    ports:
      - 9703:9703
      - 9704:9704
    environment:
      - NODE_SEED=/home/indy/scripts/seeds/nodes/nodes2-seed
    volumes:
      - node2-data:/var/lib/indy
      - ./scripts:/home/indy/scripts:ro

  node3:
    container_name: node3
    image: indy-node2:1.0
    command: 'bash -c ''./home/indy/scripts/init_node.sh 3 test-network'''
    networks:
      - anstnsp
    ports:
      - 9705:9705
      - 9706:9706
    environment:
      - NODE_SEED=/home/indy/scripts/seeds/nodes/nodes3-seed
    volumes:
      - node3-data:/var/lib/indy
      - ./scripts:/home/indy/scripts:ro

  node4:
    container_name: node4
    image: indy-node2:1.0
    command: 'bash -c ''./home/indy/scripts/init_node.sh 4 test-network'''
    networks:
      - anstnsp
    ports:
      - 9707:9707
      - 9708:9708
    environment:
      - NODE_SEED=/home/indy/scripts/seeds/nodes/nodes4-seed
    volumes:
      - node4-data:/var/lib/indy
      - ./scripts:/home/indy/scripts:ro5
 
  indy-cli:
    container_name: indy-cli
    image: indy-cli:1.0
    tty: true
    stdin_open: true 
    command: /bin/bash
    networks:
      - anstnsp 

networks:
  anstnsp:

volumes:
  node1-data:
  node2-data:
  node3-data:
  node4-data:

```
`init_node.sh` 

```shell
#!/bin/bash

set -e

HOST="${HOST:-0.0.0.0}"
NODE_NUM="${1}"
NETWORK_NAME=${2}
NODE_SEED=$(cat ${NODE_SEED})
NODE_NAME=NODE${NODE_NUM}
START_PORT=9700
NODE_PORT=$((START_PORT + ( NODE_NUM * 2 ) - 1 ))

if [ $# -ne 2 ] ; then
  echo "script $0 need 2 parameter(s): nodeNum, networkName"
  exit 1
fi

#/etc/indy/indy_config.py에 있는 네트워크의 이름을 바꿔준다.
awk '{if (index($1, "NETWORK_NAME") != 0) {print("NETWORK_NAME = \"'${NETWORK_NAME}'\"")} else print($0)}' /etc/indy/indy_config.py> /tmp/indy_config.py
mv /tmp/indy_config.py /etc/indy/indy_config.py

#NODE 초기화(init_indy_node)
if [ ! -d "/var/lib/indy/${NETWORK_NAME}" ]; then 
    echo "create dir = /var/lib/indy/${NETWORK_NAME}" 
    mkdir -p /var/lib/indy/${NETWORK_NAME}
    #[node ip] [node port] : node간 통신하기 위한 IP/PORT => node끼리만 sg 허용 해야함. 
    #[client ip] [client port] : node <->client(엔드유저) 간 통신하기 위한 IP/PORT 모든 곳에서 오는 통신 허용 해야함.
    #init_indy_node [noee별칭] [node ip] [node port] [client ip] [client port] [node seed]
    init_indy_node ${NODE_NAME} ${HOST} ${NODE_PORT} ${HOST} $(( NODE_PORT + 1 )) ${NODE_SEED} > /var/lib/indy/${NETWORK_NAME}/init_output
else 
    echo "already created dir = /var/lib/indy/${NETWORK_NAME}" 
fi

#TRUSTEE 
if [ $NODE_NUM == "1" ]; then 

  $HOME/scripts/generate_id.py $(cat $HOME/scripts/seeds/trustees/trustees$NODE_NUM-seed) >> /tmp/trustee$NODE_NUM-did-verkey

  TRUSTEE_DID=$(grep "DID" /tmp/trustee$NODE_NUM-did-verkey | awk '{print $3}')
  TRUSTEE_VERKEY=$(grep "verkey" /tmp/trustee$NODE_NUM-did-verkey | awk '{print $3}')
  echo -e "TRUSTEE_NAME$NODE_NUM,${TRUSTEE_DID},${TRUSTEE_VERKEY}" >> /tmp/trustee$NODE_NUM.csv #TREUSTEE.CSV

fi

#STEWARD
NODE_VERKEY=$(grep Verification /var/lib/indy/$NETWORK_NAME/init_output | head -n 1 |  awk '{print $4}')
NODE_IP=$HOST
BLSKEY=$(grep "BLS Public key" /var/lib/indy/$NETWORK_NAME/init_output | awk '{print $5}')
BLSKEY_POP=$(grep "Proof of possession" /var/lib/indy/$NETWORK_NAME/init_output | awk '{print $8}')

$HOME/scripts/generate_id.py $(cat $HOME/scripts/seeds/stewards/stewards$NODE_NUM-seed) >> /tmp/steward$NODE_NUM-did-verkey

STEWARD_DID=$(grep "DID" /tmp/steward$NODE_NUM-did-verkey | awk '{print $3}')
STEWARD_VERKEY=$(grep "verkey" /tmp/steward$NODE_NUM-did-verkey | awk '{print $3}')

echo -e "${STEWARD_DID},${STEWARD_VERKEY},${NODE_NAME},${NODE_IP},${NODE_PORT},${NODE_IP},$(( NODE_PORT + 1 )),${NODE_VERKEY},${BLSKEY},${BLSKEY_POP}" >> /tmp/steward$NODE_NUM.csv #STEWARD>CSV 
```

- compose 파일실행 (init_indy_node, csv파일 생성 등..)
```shell
docker-compose up -d node1 node2 node3 node4 
```

- 제네시스파일을 만들기 위해 trustees.csv, stewards.csv 파일 만들기
> 각 노드에서 만든 csv 파일들을 취합하여 최종 trustees.csv, stewards.csv 파일을 만듭니다. 
```shell
    #제네시스파일을 위한 trustees.csv, stewards.csv 파일 만들기 
    mkdir -p $HOME/myProjects/indy/my-indy-node-local/tmp
    docker cp node1:/tmp/trustee1.csv $HOME/myProjects/indy/my-indy-node-local/tmp/
    docker cp node1:/tmp/steward1.csv $HOME/myProjects/indy/my-indy-node-local/tmp/
    docker cp node2:/tmp/steward2.csv $HOME/myProjects/indy/my-indy-node-local/tmp/
    docker cp node3:/tmp/steward3.csv $HOME/myProjects/indy/my-indy-node-local/tmp/
    docker cp node4:/tmp/steward4.csv $HOME/myProjects/indy/my-indy-node-local/tmp/

    cp $PWD/scripts/createPool/stewards.csv $PWD/tmp/stewards.csv  
    cp $PWD/scripts/createPool/trustees.csv $PWD/tmp/trustees.csv  

    cat $HOME/myProjects/indy/my-indy-node-local/tmp/trustee1.csv >>  $PWD/tmp/trustees.csv
    cat $HOME/myProjects/indy/my-indy-node-local/tmp/steward1.csv >> $PWD/tmp/stewards.csv
    cat $HOME/myProjects/indy/my-indy-node-local/tmp/steward2.csv >> $PWD/tmp/stewards.csv
    cat $HOME/myProjects/indy/my-indy-node-local/tmp/steward3.csv >> $PWD/tmp/stewards.csv
    cat $HOME/myProjects/indy/my-indy-node-local/tmp/steward4.csv >> $PWD/tmp/stewards.csv

    docker cp $PWD/tmp/trustees.csv node1:/tmp 
    docker cp $PWD/tmp/stewards.csv node1:/tmp
```

- 제네시스파일 생성 및 각 노드로 복사 
(`genesis_from_files.py` 은 `indy-node` 패키지가 설치된 곳에서 실행 해야 합니다)
```shell
    #제네시스파일 생성 
    docker exec node1 cp /home/indy/scripts/genesis_from_files.py /tmp  
    docker cp $PWD/scripts/genesis_from_files.py node1:/tmp/
    docker exec node1 bash -c "cd /tmp; /tmp/genesis_from_files.py --trustees /tmp/trustees.csv --stewards /tmp/stewards.csv"
    
    #제네시스파일을 /var/lib/indy/$NETWORK_NAME 위치로 복사
    docker exec node1 cp /tmp/domain_transactions_genesis /var/lib/indy/$NETWORK_NAME/
    docker exec node1 cp /tmp/pool_transactions_genesis /var/lib/indy/$NETWORK_NAME/

    #제네시스 파일을 각 노드로 복사 (node1 -> host)
    docker cp node1:/tmp/domain_transactions_genesis $PWD/tmp
    docker cp node1:/tmp/pool_transactions_genesis $PWD/tmp
    
    #제네시스 파일을 각 노드로 복사 (host -> node2)
    docker cp $PWD/tmp/domain_transactions_genesis node2:/var/lib/indy/$NETWORK_NAME/
    docker cp $PWD/tmp/pool_transactions_genesis node2:/var/lib/indy/$NETWORK_NAME/
    #제네시스 파일을 각 노드로 복사 (host -> node3)
    docker cp $PWD/tmp/domain_transactions_genesis node3:/var/lib/indy/$NETWORK_NAME/
    docker cp $PWD/tmp/pool_transactions_genesis node3:/var/lib/indy/$NETWORK_NAME/
    #제네시스 파일을 각 노드로 복사 (host -> node4)
    docker cp $PWD/tmp/domain_transactions_genesis node4:/var/lib/indy/$NETWORK_NAME/
    docker cp $PWD/tmp/pool_transactions_genesis node4:/var/lib/indy/$NETWORK_NAME/
```
